## Statistics and Data Science 2 (Python)

# Final Project 

### Group: write your group
### Team members: list down your members

## Task 1 (Classification with prepared dataset (70% of mark)):
### Background information: 
We are constantly working to improve the quality of our products and services to grow our subscriber base and minimize churn. In our work we use a personal approach to subscribers.

To reduce churn, the company uses different channels of communication with customers. Each proposal must be addressed to a specific target group. In this task, you will have to use the available data to try to identify subscribers who will churn.


### Dataset details
Anonymized data about subscribers: subscriber service language, tariff plan, information on the volume of consumption of various operator services and others.

The **churn_rate_train.csv** file contains information to build the model.

Row format: 
- 3 categorical features (C1, C2, C3)
- 23 numeric features (N1, ..., N23) 
- the target variable - TARGET


### Task
Describe the stages of building a model, build a model, evaluate it and tell the business how to apply it, that is, a business interpretation is needed.

*Note: this is how the task was originally structured, you can use it as a guidance.*

## Marking scheme
1. Data Preparation - 20%
2. Model (variety, complexity, tunning) - 30%
3. Imbalance (approaching this issue) - 20%
4. Code quality - 10%
5. Results and Defence - 20%

*Note: add comments and description of the approaches that you use, for example, for resolving the problem of imbalanced data. Write descriptions of techniques that you apply, and you should understand them as well.*

## Hints:
1. You are given with train dataset (contains both features and target), and test dataset (contains only features). For test dataset you should predict Target, and provide your predictions as Pandas Array. I will evaluate your predictions myself.
2. To estimate key metric on test dataset, I suggest to use 5-fold Cross Validation. **Note: you don't have access to Y-test, hence you can't calculate metric on test dataset. We are simulating real life competition.**
3. You should take F1-score as your main metric.
4. To get good mark, I recommend you:
- to try at least 3 models with default settings
- to optimize at least 1 model (i.e. do hyperparameter tuning)
- to try at least 3 different methods to tackle imbalanceness
- to build consolidated table with all results
- to predict based on best obtained model

In [1]:
import pandas as pd

In [7]:
# This is your dataset for training
df_train = pd.read_csv('../churn_train.csv')
df_train.head()
len(df_train['C3'].unique())

3

In [3]:
# This is your dataset for testing, but without TARGET
# For this data you should obtain predicted Y
df_test = pd.read_csv('X_churn_test.csv')
df_test.head()

,C1,C2,C3,N1,N2,N3,N4,N5,N6,N7,...,N14,N15,N16,N17,N18,N19,N20,N21,N22,N23
0,3531383839343233,343439,31,0.00,1210.58,9679.97,657.10,331.60,0.00,6.03,...,94,31,0,5,94,26,94,31,0,0
1,3235303635303039,3434,31,0.00,0.00,0.00,0.08,1.60,0.00,0.00,...,3,2,0,0,2,2,3,2,0,0
2,3433373930343038,343433,31,0.18,324.36,3611.99,129.02,677.98,5.12,0.00,...,7,21,3,0,4,21,7,21,0,0
3,3532373635343736,343637,31,0.00,0.00,0.00,69.57,72.17,0.00,5.88,...,20,21,0,3,20,18,20,21,0,0
4,3331323035323031,313435,33,189.21,4340.27,0.00,305.88,420.83,6.73,8.27,...,96,79,7,11,89,68,96,79,0,0

## Task 2 (Clustering with any dataset (30% of mark))
1. Select any dataset that will suit for clustering
2. Observe your data
3. Apply some data preparation
4. Apply clustering model
5. Visualise your obtained clusters

## Marking scheme
1. Data Preparation - 20%
2. Kmeans model - 30%
3. Visualisation - 20%
4. Code quality - 10%
5. Results and Defence - 20%

*Note: add comments and description of the approaches that you use, for example, for resolving the problem of imbalanced data. Write descriptions of techniques that you apply, and you should understand them as well.*

In [4]:
# code here

In [5]:
# code here

In [6]:
# code here

In [7]:
# code here